### ISSUE TITLE
ListingTable PropTypes Syntax

### ISSUE THREAD

**Issue by mlodato517** [massgov/mayflower#422]
It looks like `mayflower/react/src/components/molecules/ListingTable/index.js` has
```
ListingTable.propTypes = {
...
items: PropTypes.arrayOf(PropTypes.oneOf(PropTypes.string, PropTypes.object))
```
which should probably be
```
items: PropTypes.arrayOf(PropTypes.oneOf([PropTypes.string, PropTypes.object]))
```
as it results in `Warning: Invalid argument supplied to oneOf, expected an instance of array.`

Also, there's a small type of "lable" instead of "label"

**Comment by clairesunstudio** [comment]
Thanks for your feedback! The console warning has been addressed in https://github.com/massgov/mayflower/pull/656
