### ISSUE TITLE
[Implementation] add domain to search https://massculturalcouncil.org/

### ISSUE THREAD

**Issue by Cathwaldron** [massgov/mayflower#650]
Before opening an issue:

- Refer to the [Mayflower Implementation List](https://massgovdigital.gitbook.io/mayflower/)
- [Search for duplicate or closed issues](https://github.com/massgov/mayflower/issues?utf8=%E2%9C%93&q=is%3Aissue)

When submitting your request, include:

* A link to the application
* Your name or alias and contact URL or email address
* The implementation’s target language and/or framework
* The code repository if it is in Github or equivalent (if public)
* What type of Mayflower implementation you are using
  - Mayflower Patternlab
  - Mayflower React
  - Mayflower as Markup
  - Mayflower as Branding
* What Mayflower Design System version you are using 
* Any useful caveats or other notes

**Comment by avrilpearl** [comment]
@Cathwaldron --> your site has been added to the sites we search in the internal mass.gov search application (e.g. https://search.mass.gov/?q=cultural%20council&page=1) and I have also updated our documentation to include your site in the list of sites we search here https://massgovdigital.gitbook.io/mayflower/guidelines/search-and-structured-data#adding-your-domain-to-the-search-mass-gov-cse

Please let me know if this meets your request! 

Have a great 4th of July!

Tanks,
Sienna
