### ISSUE TITLE
[Implementation] add a form to capture the add domain to search https://massgovdigital.gitbook.io/mayflower/guidelines/search-and-structured-data#adding-structured-metatags-to-your-website

### ISSUE THREAD

**Issue by Cathwaldron** [massgov/mayflower#651]
Before opening an issue:

- Refer to the [Mayflower Implementation List](https://massgovdigital.gitbook.io/mayflower/)
- [Search for duplicate or closed issues](https://github.com/massgov/mayflower/issues?utf8=%E2%9C%93&q=is%3Aissue)

When submitting your request, include:

* A link to the application
* Your name or alias and contact URL or email address
* The implementation’s target language and/or framework
* The code repository if it is in Github or equivalent (if public)
* What type of Mayflower implementation you are using
  - Mayflower Patternlab
  - Mayflower React
  - Mayflower as Markup
  - Mayflower as Branding
* What Mayflower Design System version you are using 
* Any useful caveats or other notes

**Comment by avrilpearl** [comment]
Hi @Cathwaldron ,

Just following up on this request. Is your suggestion that you would like to be able to request adding your domain to search.mass.gov via a form versus interacting with a github issue?

Thanks in advance for the clarification,
Sienna

**Comment by Cathwaldron** [comment]
Hello Ma’am, 
Yes, that is my suggestion. 

Perhaps the requester could be offered a choice to submit the request either as a Github issue or as a form submission.

Justification for this request: Not every developer has a Github account, as many are using Gitlab, Bitbucket, or other alternatives to Github.
Moreover, a request to index an agency site may be initiated by a non-developer who may be completely unfamiliar with Github.

Thank you for considering this request. 

Sincerely,

Catherine Waldron
Web Development, Sales Operations, Customer Support and Training

cathwaldron@gmail.com
catherine@webrenovation.biz
Mobile: 617-513-6789

**Comment by clairesunstudio** [comment]
Hi @Cathwaldron,

Thanks for the feedback and sorry for the late response! If you are working with an agency that would like to be added to the search.mass.gov search engine, they could also submit a ticket through "service-now", the state's internal ticketing system. Currently, we have two public-facing communication channels for Mayflower:
- [Create an issue on github](https://github.com/massgov/mayflower/issues/new)
- [Join the Mayflower Slack](https://join.slack.com/t/mayflowerdesignsystem/shared_invite/enQtNTc0MjMwMjcwMzU0LWQ4MjA2YTUzY2EzMWJhNjI2ZThhNDJhOTdiOGE1OTFjMzVkMWU2ODEwNDRlOTkxOWI2NzdkMThiNGEwZTk5NzU)

I will close this issue for now. Let me know if you have other questions. Thanks!
