### ISSUE TITLE
React package installation instructions are incomplete

### ISSUE THREAD

**Issue by sawyerh** [massgov/mayflower#861]
The documentation for the React package currently mentions installing the package, importing a component, and including its JSX. However, it appears that some components also include CSS-in-JS, which requires additional installation steps to support. If the NPM package doesn't work out of the box, it'd be helpful to understand what are a project's build system prerequisites in order to support the React package. Thanks!

**Comment by clairesunstudio** [comment]
Hi @sawyerh thanks for flagging this! We have a mayflower react starter using CRA, you can check out this repo for reference --> https://github.com/massgov/mayflower-react-starter/
I will do some package updates tomorrow so that you can leverage it directly. Let me know if this helps or if you have more questions.

**Comment by sawyerh** [comment]
@clairesunstudio Thanks for the link! I think what I am looking for is a bit different, which is instructions for a team if they're not using the starter or CRA to develop their React application (for example, if they're using [Next](https://nextjs.org/)). How would a team like that setup their build system so that they can use the Mayflower React library?

Looking into CRA a bit, [it looks like](https://github.com/facebook/create-react-app/blob/94932bedc09976aeac43615d95906aa2dcfefa1f/packages/react-scripts/config/webpack.config.js#L93) a team like that might need to add specific Webpack dependencies and configurations in order to play nice with how Mayflower imports CSS files in the JS files?

**Comment by clairesunstudio** [comment]
@sawyerh I see, we don't have examples using Next.js. Are you running into issues specifically with server-side rendering css-in-js components?  We have been importing compiled css into our components in order to share scss with our patternlab component library and we don't intend to use css-in-js. Can you point me to an example for
> However, it appears that some components also include CSS-in-JS, which requires additional installation steps to support.

Can you show me the errors you are getting or add me to the repo so I can better understand the issue? Thanks!

**Comment by clairesunstudio** [comment]
Do you mean `import './style.css';`? 
It seems like adding this package would solve that https://github.com/zeit/next-plugins/tree/master/packages/next-css

**Comment by sawyerh** [comment]
Hi, I've created a bare minimum React application to demonstrate the issue I'm trying to communicate. Does this help? Additional instructions to get it running in the README: https://github.com/sawyerh/mayflower-issue-861

**Comment by clairesunstudio** [comment]
Hi @sawyerh since you are configuring your own webpack, you will need add loaders to handle image files and css :
`npm install --save-dev css-loader svg-inline-loader file-loader`

```
module.exports = {
  entry: {
    client: ["./src/index.js"]
  },
  mode: "development",
  module: {
    rules: [
      // Transform ES6 and React with Babel
      {
        test: /\.js$/,
        include: [path.resolve(__dirname, "src")],
        loader: require.resolve("babel-loader")
      },
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.svg$/,
        loader: 'svg-inline-loader'
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: 'file-loader',
          },
        ],
      }
    ]
  },
...
}
```

**Comment by sawyerh** [comment]
@clairesunstudio Woot, those are the instructions I needed. Looks like that gets the React package to work for custom Webpacks, or for frameworks that don't come with those dependencies:

![image](https://user-images.githubusercontent.com/371943/72815084-18303580-3c34-11ea-8c53-7d47f40b6d89.png)

**Comment by clairesunstudio** [comment]
@sawyerh Awesome! I will follow up with adding this to the documentation. Do you mind if I use your demo code as an example?

**Comment by sawyerh** [comment]
@clairesunstudio For sure, feel free 👍
